config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :games

  root to: 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user.email
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @user = current_user
    @game = @user.games.create(game_params)

    if @game.save
      redirect_to @game
    else
      render 'new'
    end
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render 'edit'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_path
  end

  private
    def game_params
      params.require(:game).permit(:name, :description, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game, local: true do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :image %><br>
    <%= form.text_field :image %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/games/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1><%= @user %>'s games</h1>

<table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th colspan="3"></th>
  </tr>

  <% @games.each do |game| %>
   <tr>
      <td>
          <% if game.image %>
              <%= link_to game_path(game) do %>
                  <%= image_tag game.image %>
              <% end %>
          <% end %>
      </td>
      <td><%= game.name %></td>
      <td><%= game.description %></td>
      <td><%= link_to 'Show', game_path(game) %></td>
      <td><%= link_to 'Edit', edit_game_path(game) %></td>
      <td><%= link_to 'Delete', game_path(game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

  <tr>
    <td><%= link_to 'New', new_game_path %></td>
  </tr>
</table>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Cancel', games_path %>

app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @game.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <%= link_to 'Edit', edit_game_path(@game) %>
  <%= link_to 'Delete', game_path(@game),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', games_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBoardgames</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="content activity-feed">
  <div class="row feed-item">
    Keri and Joe played <span class="game-link">Settlers of Catan</span> on Tuesday.
  </div>

  <div class="row feed-item">
    Arin added <span class="game-link">5</span> games to his collection.
  </div>

  <div class="row feed-item">
    You and Keri became friends.
  </div>
</div>

<div class="footer nav-links">
  <a href="">
    <i class="icon">S</i>
  </a>
  <a href="">
    <i class="icon">R</i>
  </a>
  <%= link_to(controller: 'games') do %>
    <i class="icon">G</i>
  <% end %>
</div>